// <auto-generated />
// Generated by src/Generator/generate-bit-string-types.js

namespace Baclib.Bacnet.Types.Application;

/// <summary>
/// Represents BACnet bit string BACnetAuditOperationFlags.
/// </summary>
public readonly partial record struct AuditOperationFlags : IBitString
{
    /// <summary>
    /// Minimum permitted number of bits.
    /// </summary>
    public const int MinLength = 16;

    /// <summary>
    /// Maximum permitted number of bits.
    /// </summary>
    public const int MaxLength = 64;

    private readonly byte _count;

    /// <inheritdoc/>
    int IReadOnlyCollection<bool>.Count => _count;

    /// <inheritdoc/>
    public int Length => _count;

    /// <inheritdoc/>
    public int MinCount => MinLength;

    /// <inheritdoc/>
    public int MaxCount => MaxLength;

    /// <summary>
    /// Gets the underlying bit container.
    /// </summary>
    public ulong Flags { get; }

    /// <summary>
    /// Initializes a new instance of <see cref="AuditOperationFlags"/> with a variable number of bits.
    /// </summary>
    /// <param name="flags">Underlying ulong bit container in LSB-first bit order.</param>
    /// <param name="count">Number of valid bits in <paramref name="flags"/>. Valid range is <see cref="MinLength"/> to <see cref="MaxLength"/>.</param>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="count"/> is out of range.</exception>
    public AuditOperationFlags(ulong flags, byte count)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan((int)count, MinLength, nameof(count));
        if (MaxLength != int.MaxValue)
        {
            ArgumentOutOfRangeException.ThrowIfGreaterThan((int)count, MaxLength, nameof(count));
        }

        _count = count;
        Flags = MaskToCount(flags, (int)count);
    }

    /// <summary>
    /// Read operation.
    /// </summary>
    public bool Read => this[0];

    /// <summary>
    /// Write operation.
    /// </summary>
    public bool Write => this[1];

    /// <summary>
    /// Create operation.
    /// </summary>
    public bool Create => this[2];

    /// <summary>
    /// Delete operation.
    /// </summary>
    public bool Delete => this[3];

    /// <summary>
    /// Life safety operation.
    /// </summary>
    public bool LifeSafety => this[4];

    /// <summary>
    /// Acknowledge alarm operation.
    /// </summary>
    public bool AcknowledgeAlarm => this[5];

    /// <summary>
    /// Device disable communication operation.
    /// </summary>
    public bool DeviceDisableComm => this[6];

    /// <summary>
    /// Device enable communication operation.
    /// </summary>
    public bool DeviceEnableComm => this[7];

    /// <summary>
    /// Device reset operation.
    /// </summary>
    public bool DeviceReset => this[8];

    /// <summary>
    /// Device backup operation.
    /// </summary>
    public bool DeviceBackup => this[9];

    /// <summary>
    /// Device restore operation.
    /// </summary>
    public bool DeviceRestore => this[10];

    /// <summary>
    /// Subscription operation.
    /// </summary>
    public bool Subscription => this[11];

    /// <summary>
    /// Notification operation.
    /// </summary>
    public bool Notification => this[12];

    /// <summary>
    /// Auditing failure operation.
    /// </summary>
    public bool AuditingFailure => this[13];

    /// <summary>
    /// Network changes operation.
    /// </summary>
    public bool NetworkChanges => this[14];

    /// <summary>
    /// General operation.
    /// </summary>
    public bool General => this[15];

    /// <summary>
    /// Gets whether the bit at the specified zero-based index is set.
    /// </summary>
    /// <param name="index">Zero-based bit index.</param>
    /// <returns><see langword="true"/> when the bit is set; otherwise <see langword="false"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="index"/> is outside the range <c>0..Count-1</c>.</exception>
    public bool this[int index]
    {
        get
        {
            ArgumentOutOfRangeException.ThrowIfNegative(index, nameof(index));
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(index, Length, nameof(index));
            return (Flags & (1ul << index)) != 0;
        }
    }

    /// <summary>
    /// Clears all bits above the provided bit count and returns the normalized value.
    /// </summary>
    /// <param name="flags">Input bit container.</param>
    /// <param name="count">Number of valid low-order bits to preserve.</param>
    /// <returns>Masked flag value containing only the valid bits.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="count"/> is outside the supported bit range for this storage type.</exception>
    private static ulong MaskToCount(ulong flags, int count)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(count, nameof(count));
        ArgumentOutOfRangeException.ThrowIfGreaterThan(count, 64, nameof(count));

        if (count == 0) return 0;
        if (count >= 64) return flags;
        ulong mask = (1ul << count) - 1ul;
        return flags & mask;
    }
}

