// <auto-generated />
// Generated by src/Generator/generate-bit-string-types.js

namespace Baclib.Bacnet.Types.Application;

public partial record class AuthorizationScope
{
    /// <summary>
    /// Represents BACnet bit string standard.
    /// </summary>
    public readonly partial record struct TStandard : IBitString
    {
        /// <summary>
        /// Fixed number of bits for this type.
        /// </summary>
        public const int FixedLength = 24;
    
        /// <inheritdoc/>
        int IReadOnlyCollection<bool>.Count => FixedLength;
    
        /// <inheritdoc/>
        public int Length => FixedLength;
    
        /// <inheritdoc/>
        public int MinCount => FixedLength;
    
        /// <inheritdoc/>
        public int MaxCount => FixedLength;
    
        /// <summary>
        /// Gets the underlying bit container.
        /// </summary>
        public uint Flags { get; }
    
        /// <summary>
        /// Initializes a new instance of <see cref="TStandard"/> with a fixed bit length.
        /// </summary>
        /// <param name="flags">Underlying uint bit container in LSB-first bit order.</param>
        public TStandard(uint flags)
        {
            Flags = MaskToCount(flags, FixedLength);
        }
    
        /// <summary>
        /// Permission to view or read data.
        /// </summary>
        public bool View => this[0];
    
        /// <summary>
        /// Permission to adjust or modify operational values.
        /// </summary>
        public bool Adjust => this[1];
    
        /// <summary>
        /// Permission to control device operation.
        /// </summary>
        public bool Control => this[2];
    
        /// <summary>
        /// Permission to override normal operation.
        /// </summary>
        public bool Override_ => this[3];
    
        /// <summary>
        /// Permission to configure device settings.
        /// </summary>
        public bool Config => this[4];
    
        /// <summary>
        /// Permission to bind or associate objects.
        /// </summary>
        public bool Bind => this[5];
    
        /// <summary>
        /// Permission to install or commission devices.
        /// </summary>
        public bool Install => this[6];
    
        /// <summary>
        /// Permission to perform authentication operations.
        /// </summary>
        public bool Auth => this[7];
    
        /// <summary>
        /// Permission to access infrastructure operations.
        /// </summary>
        public bool Infrastructure => this[8];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved9 => this[9];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved10 => this[10];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved11 => this[11];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved12 => this[12];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved13 => this[13];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved14 => this[14];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved15 => this[15];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved16 => this[16];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved17 => this[17];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved18 => this[18];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved19 => this[19];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved20 => this[20];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved21 => this[21];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved22 => this[22];
    
        /// <summary>
        /// Reserved for future use.
        /// </summary>
        public bool Reserved23 => this[23];
    
        /// <summary>
        /// Gets whether the bit at the specified zero-based index is set.
        /// </summary>
        /// <param name="index">Zero-based bit index.</param>
        /// <returns><see langword="true"/> when the bit is set; otherwise <see langword="false"/>.</returns>
        /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="index"/> is outside the range <c>0..Count-1</c>.</exception>
        public bool this[int index]
        {
            get
            {
                ArgumentOutOfRangeException.ThrowIfNegative(index, nameof(index));
                ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(index, Length, nameof(index));
                return (Flags & (1u << index)) != 0;
            }
        }
    
        /// <summary>
        /// Clears all bits above the provided bit count and returns the normalized value.
        /// </summary>
        /// <param name="flags">Input bit container.</param>
        /// <param name="count">Number of valid low-order bits to preserve.</param>
        /// <returns>Masked flag value containing only the valid bits.</returns>
        /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="count"/> is outside the supported bit range for this storage type.</exception>
        private static uint MaskToCount(uint flags, int count)
        {
            ArgumentOutOfRangeException.ThrowIfNegative(count, nameof(count));
            ArgumentOutOfRangeException.ThrowIfGreaterThan(count, 32, nameof(count));
    
            if (count == 0) return 0;
            if (count >= 32) return flags;
            uint mask = (1u << count) - 1u;
            return flags & mask;
        }
    }
    
}

