// SPDX-FileCopyrightText: Copyright 2024-2026, The BAClib Initiative and Contributors
// SPDX-License-Identifier: EPL-2.0

namespace Baclib.Bacnet.Types.Application;

public partial record class GetEnrollmentSummaryAck
{
    /// <summary>
    /// Represents the sequence item as defined in ANSI/ASHRAE 135-2024 Clause 21.
    /// </summary>
    public partial record class TItem
    {
        /// <summary>
        /// The object identifier of the enrolled event-generating object.
        /// </summary>
        public required ObjectIdentifier ObjectIdentifier { get; init; }
    
        /// <summary>
        /// The type of event generated by this object.
        /// </summary>
        public required EventType EventType { get; init; }
    
        /// <summary>
        /// The current event state of the object.
        /// </summary>
        public required EventState EventState { get; init; }
    
        /// <summary>
        /// The priority of the event notification.
        /// </summary>
        public required Unsigned8 Priority { get; init; }
    
        /// <summary>
        /// Optional notification class identifier for the event.
        /// </summary>
        public Optional<Unsigned> NotificationClass { get; init; }
    }
}
