// <auto-generated />
// Generated by src/Generator/generate-bit-string-types.js

namespace Baclib.Bacnet.Types.Application;

/// <summary>
/// Represents BACnet bit string BACnetServicesSupported.
/// </summary>
public readonly partial record struct ServicesSupported : IBitString
{
    /// <summary>
    /// Minimum permitted number of bits.
    /// </summary>
    public const int MinLength = 35;

    /// <summary>
    /// Maximum permitted number of bits.
    /// </summary>
    public const int MaxLength = 512;

    private readonly ushort _count;

    /// <inheritdoc/>
    int IReadOnlyCollection<bool>.Count => _count;

    /// <inheritdoc/>
    public int Length => _count;

    /// <inheritdoc/>
    public int MinCount => MinLength;

    /// <inheritdoc/>
    public int MaxCount => MaxLength;

    /// <summary>
    /// Gets the underlying bit container.
    /// </summary>
    public byte[] Flags { get; }

    /// <summary>
    /// Initializes a new instance of <see cref="ServicesSupported"/> with a variable number of bits.
    /// </summary>
    /// <param name="flags">Bit payload bytes in LSB-first bit order.</param>
    /// <param name="count">Number of valid bits in <paramref name="flags"/>. Valid range is <see cref="MinLength"/> to <see cref="MaxLength"/>.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="flags"/> is <see langword="null"/>.</exception>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="count"/> is out of range, or when <paramref name="flags"/> is shorter than required for <paramref name="count"/>.</exception>
    public ServicesSupported(byte[] flags, ushort count)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan((int)count, MinLength, nameof(count));
        if (MaxLength != int.MaxValue)
        {
            ArgumentOutOfRangeException.ThrowIfGreaterThan((int)count, MaxLength, nameof(count));
        }

        int requiredBytes = GetRequiredByteCount((int)count);
        ArgumentNullException.ThrowIfNull(flags, nameof(flags));
        ArgumentOutOfRangeException.ThrowIfLessThan(flags.Length, requiredBytes, nameof(flags));

        _count = count;
        Flags = new byte[requiredBytes];
        Array.Copy(flags, Flags, requiredBytes);
    }

    /// <summary>
    /// Acknowledge alarm service.
    /// </summary>
    public bool AcknowledgeAlarm => this[0];

    /// <summary>
    /// Confirmed COV notification service.
    /// </summary>
    public bool ConfirmedCovNotification => this[1];

    /// <summary>
    /// Confirmed event notification service.
    /// </summary>
    public bool ConfirmedEventNotification => this[2];

    /// <summary>
    /// Get alarm summary service.
    /// </summary>
    public bool GetAlarmSummary => this[3];

    /// <summary>
    /// Get enrollment summary service.
    /// </summary>
    public bool GetEnrollmentSummary => this[4];

    /// <summary>
    /// Subscribe COV service.
    /// </summary>
    public bool SubscribeCov => this[5];

    /// <summary>
    /// Atomic read file service.
    /// </summary>
    public bool AtomicReadFile => this[6];

    /// <summary>
    /// Atomic write file service.
    /// </summary>
    public bool AtomicWriteFile => this[7];

    /// <summary>
    /// Add list element service.
    /// </summary>
    public bool AddListElement => this[8];

    /// <summary>
    /// Remove list element service.
    /// </summary>
    public bool RemoveListElement => this[9];

    /// <summary>
    /// Create object service.
    /// </summary>
    public bool CreateObject => this[10];

    /// <summary>
    /// Delete object service.
    /// </summary>
    public bool DeleteObject => this[11];

    /// <summary>
    /// Read property service.
    /// </summary>
    public bool ReadProperty => this[12];

    /// <summary>
    /// Read property multiple service.
    /// </summary>
    public bool ReadPropertyMultiple => this[14];

    /// <summary>
    /// Write property service.
    /// </summary>
    public bool WriteProperty => this[15];

    /// <summary>
    /// Write property multiple service.
    /// </summary>
    public bool WritePropertyMultiple => this[16];

    /// <summary>
    /// Device communication control service.
    /// </summary>
    public bool DeviceCommunicationControl => this[17];

    /// <summary>
    /// Confirmed private transfer service.
    /// </summary>
    public bool ConfirmedPrivateTransfer => this[18];

    /// <summary>
    /// Confirmed text message service.
    /// </summary>
    public bool ConfirmedTextMessage => this[19];

    /// <summary>
    /// Reinitialize device service.
    /// </summary>
    public bool ReinitializeDevice => this[20];

    /// <summary>
    /// VT open service.
    /// </summary>
    public bool VtOpen => this[21];

    /// <summary>
    /// VT close service.
    /// </summary>
    public bool VtClose => this[22];

    /// <summary>
    /// VT data service.
    /// </summary>
    public bool VtData => this[23];

    /// <summary>
    /// I-Am service.
    /// </summary>
    public bool IAm => this[26];

    /// <summary>
    /// I-Have service.
    /// </summary>
    public bool IHave => this[27];

    /// <summary>
    /// Unconfirmed COV notification service.
    /// </summary>
    public bool UnconfirmedCovNotification => this[28];

    /// <summary>
    /// Unconfirmed event notification service.
    /// </summary>
    public bool UnconfirmedEventNotification => this[29];

    /// <summary>
    /// Unconfirmed private transfer service.
    /// </summary>
    public bool UnconfirmedPrivateTransfer => this[30];

    /// <summary>
    /// Unconfirmed text message service.
    /// </summary>
    public bool UnconfirmedTextMessage => this[31];

    /// <summary>
    /// Time synchronization service.
    /// </summary>
    public bool TimeSynchronization => this[32];

    /// <summary>
    /// Who-Has service.
    /// </summary>
    public bool WhoHas => this[33];

    /// <summary>
    /// Who-Is service.
    /// </summary>
    public bool WhoIs => this[34];

    /// <summary>
    /// Read range service.
    /// </summary>
    public bool ReadRange => this[35];

    /// <summary>
    /// UTC time synchronization service.
    /// </summary>
    public bool UtcTimeSynchronization => this[36];

    /// <summary>
    /// Life safety operation service.
    /// </summary>
    public bool LifeSafetyOperation => this[37];

    /// <summary>
    /// Subscribe COV property service.
    /// </summary>
    public bool SubscribeCovProperty => this[38];

    /// <summary>
    /// Get event information service.
    /// </summary>
    public bool GetEventInformation => this[39];

    /// <summary>
    /// Write group service.
    /// </summary>
    public bool WriteGroup => this[40];

    /// <summary>
    /// Subscribe COV property multiple service.
    /// </summary>
    public bool SubscribeCovPropertyMultiple => this[41];

    /// <summary>
    /// Confirmed COV notification multiple service.
    /// </summary>
    public bool ConfirmedCovNotificationMultiple => this[42];

    /// <summary>
    /// Unconfirmed COV notification multiple service.
    /// </summary>
    public bool UnconfirmedCovNotificationMultiple => this[43];

    /// <summary>
    /// Confirmed audit notification service.
    /// </summary>
    public bool ConfirmedAuditNotification => this[44];

    /// <summary>
    /// Audit log query service.
    /// </summary>
    public bool AuditLogQuery => this[45];

    /// <summary>
    /// Unconfirmed audit notification service.
    /// </summary>
    public bool UnconfirmedAuditNotification => this[46];

    /// <summary>
    /// Who-Am-I service.
    /// </summary>
    public bool WhoAmI => this[47];

    /// <summary>
    /// You-Are service.
    /// </summary>
    public bool YouAre => this[48];

    /// <summary>
    /// Auth request service.
    /// </summary>
    public bool AuthRequest => this[49];

    /// <summary>
    /// Gets whether the bit at the specified zero-based index is set.
    /// </summary>
    /// <param name="index">Zero-based bit index.</param>
    /// <returns><see langword="true"/> when the bit is set; otherwise <see langword="false"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="index"/> is outside the range <c>0..Count-1</c>.</exception>
    public bool this[int index]
    {
        get
        {
            ArgumentOutOfRangeException.ThrowIfNegative(index, nameof(index));
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(index, Length, nameof(index));

            int byteIndex = index / 8;
            int bitOffset = index % 8;
            return (Flags[byteIndex] & (1 << bitOffset)) != 0;
        }
    }

    /// <summary>
    /// Calculates the minimum number of bytes required to store the specified number of bits.
    /// </summary>
    /// <param name="bitCount">Bit count to convert to a byte count.</param>
    /// <returns>Required byte count.</returns>
    private static int GetRequiredByteCount(int bitCount)
    {
        if (bitCount <= 0)
        {
            return 0;
        }

        return (bitCount + 7) / 8;
    }
}

