// <auto-generated />
// Generated by src/Generator/generate-bit-string-types.js

namespace Baclib.Bacnet.Types.Application;

/// <summary>
/// Represents BACnet bit string BACnetStatusFlags.
/// </summary>
public readonly partial record struct StatusFlags : IBitString
{
    /// <summary>
    /// Fixed number of bits for this type.
    /// </summary>
    public const int FixedLength = 4;

    /// <inheritdoc/>
    int IReadOnlyCollection<bool>.Count => FixedLength;

    /// <inheritdoc/>
    public int Length => FixedLength;

    /// <inheritdoc/>
    public int MinCount => FixedLength;

    /// <inheritdoc/>
    public int MaxCount => FixedLength;

    /// <summary>
    /// Gets the underlying bit container.
    /// </summary>
    public byte Flags { get; }

    /// <summary>
    /// Initializes a new instance of <see cref="StatusFlags"/> with a fixed bit length.
    /// </summary>
    /// <param name="flags">Underlying byte bit container in LSB-first bit order.</param>
    public StatusFlags(byte flags)
    {
        Flags = MaskToCount(flags, FixedLength);
    }

    /// <summary>
    /// Object is in alarm.
    /// </summary>
    public bool InAlarm => this[0];

    /// <summary>
    /// Object is in fault condition.
    /// </summary>
    public bool Fault => this[1];

    /// <summary>
    /// Object is overridden.
    /// </summary>
    public bool Overridden => this[2];

    /// <summary>
    /// Object is out of service.
    /// </summary>
    public bool OutOfService => this[3];

    /// <summary>
    /// Gets whether the bit at the specified zero-based index is set.
    /// </summary>
    /// <param name="index">Zero-based bit index.</param>
    /// <returns><see langword="true"/> when the bit is set; otherwise <see langword="false"/>.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="index"/> is outside the range <c>0..Count-1</c>.</exception>
    public bool this[int index]
    {
        get
        {
            ArgumentOutOfRangeException.ThrowIfNegative(index, nameof(index));
            ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(index, Length, nameof(index));
            return (Flags & (1 << index)) != 0;
        }
    }

    /// <summary>
    /// Clears all bits above the provided bit count and returns the normalized value.
    /// </summary>
    /// <param name="flags">Input bit container.</param>
    /// <param name="count">Number of valid low-order bits to preserve.</param>
    /// <returns>Masked flag value containing only the valid bits.</returns>
    /// <exception cref="ArgumentOutOfRangeException">Thrown when <paramref name="count"/> is outside the supported bit range for this storage type.</exception>
    private static byte MaskToCount(byte flags, int count)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(count, nameof(count));
        ArgumentOutOfRangeException.ThrowIfGreaterThan(count, 8, nameof(count));

        if (count == 0) return 0;
        if (count >= 8) return flags;
        byte mask = (byte)((1 << count) - 1);
        return (byte)(flags & mask);
    }
}

